import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import SidebarLeft from "@/components/SidebarLeft";
import SidebarRight from "@/components/SidebarRight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Institute Partner Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-slate-100 text-black">
        <div className="max-w-[1280px] mx-auto bg-white min-h-screen shadow-lg flex flex-col">
          <Header />
          <Navbar />
          
          <div className="flex flex-col lg:flex-row gap-5 p-4 md:p-5 flex-grow">
            {/* Left Sidebar */}
            <aside className="w-full lg:w-[260px] flex-shrink-0">
              <SidebarLeft />
            </aside>
            
            {/* Main Content */}
            <main className="flex-1 w-full min-w-0">
              {children}
            </main>
            
            {/* Right Sidebar */}
            <aside className="w-full lg:w-[260px] flex-shrink-0">
              <SidebarRight />
            </aside>
          </div>
        </div>
      </body>
    </html>
  );
}
